### ISSUE TITLE
Grade table add points error in exam class

### ISSUE THREAD

**Issue by ribeaud** [XaF/exam#1]
When assigning points to both the question AND the parts of that question, **gradetable** generation displays the points for that question twice as much the correct value as it adds BOTH the points for question AND the parts therein.

**Comment by xaf** [comment]
Hi,

This is normal, you have to use `\noaddpoints` and then `\addpoints` around sections to avoid counting some points in double. This is how the class has been built.

A more up to date version is available on the website of the original author: http://www-math.mit.edu/~psh/#ExamCls - My github is merely for changes I've done for my needs, as the author does not seem to have a git available for his class :)

**Comment by ribeaud** [comment]
Hi,
Got it. Thank you for the hint.
Have an enjoyable day.
Regards,
christian
